'use strict';
const $=id=>document.getElementById(id);
const labels={single:'シングル',multi:'マルチ',metal:'GPU',guard:'防御・充電'};
const costs={single:0,multi:2,metal:3,guard:0};
const base={single:12,multi:20,metal:26};
let chips=[],p,e,turn,plan,finished;
const fmt=n=>new Intl.NumberFormat('ja-JP').format(n);
function chosen(id){return chips.find(c=>c.id===$(id).value);}
function compare(){const a=chosen('player'),b=chosen('enemy');$('compare').replaceChildren();for(const k of Object.keys(base)){const row=document.createElement('div');row.className='comparison';const max=Math.max(a.bench[k],b.bench[k]);row.innerHTML=`<div><strong>${fmt(a.bench[k])}</strong><div class="track"><div class="fill" style="width:${a.bench[k]/max*100}%"></div></div></div><div class="label">${labels[k]}<br>自分 / 相手 ${(a.bench[k]/b.bench[k]).toFixed(2)}×</div><div class="right"><strong>${fmt(b.bench[k])}</strong><div class="track"><div class="fill" style="width:${b.bench[k]/max*100}%"></div></div></div>`;$('compare').append(row);}const specs=document.createElement('div');specs.className='specs';for(const c of [a,b]){const el=document.createElement('p');el.textContent=`CPU ${c.cpu}コア / GPU ${c.gpu}コア / 最大${Math.max(...c.memory)}GB · 代表機種：${c.benchDevice}`;specs.append(el);}$('compare').append(specs);}
function damage(a,b,k){return Math.round(base[k]*Math.max(.4,Math.min(2.5,Math.sqrt(a.chip.bench[k]/b.chip.bench[k]))));}
function enemyPlan(){if(e.energy<2)return 'guard';const available=Object.keys(base).filter(k=>costs[k]<=e.energy);return available.sort((a,b)=>damage(e,p,b)-damage(e,p,a))[0];}
function render(){for(const [prefix,f] of [['p',p],['e',e]]){$(prefix+'-hp').textContent=`${f.hp} / 100`;$(prefix+'-bar').value=f.hp;$(prefix+'-energy').textContent=`エネルギー ${f.energy} / 6`;}$('round').textContent=`TURN ${turn} / 20`;$('intent').textContent=finished?'対戦終了':`相手の予告：${labels[plan]}${plan==='guard'?'':` · 通常 ${damage(e,p,plan)} ダメージ`}`;document.querySelectorAll('[data-move]').forEach(b=>{b.disabled=finished||p.energy<costs[b.dataset.move];if(base[b.dataset.move])b.title=`通常 ${damage(p,e,b.dataset.move)} ダメージ`;});}
function start(){p={chip:chosen('player'),hp:100,energy:4};e={chip:chosen('enemy'),hp:100,energy:4};turn=1;finished=false;$('setup').hidden=true;$('battle').hidden=false;$('retry').hidden=true;$('result').textContent='';$('log').replaceChildren();for(const [prefix,f] of [['p',p],['e',e]]){$(prefix+'-name').textContent=f.chip.chip;$(prefix+'-die').innerHTML='<i></i>'.repeat(Math.min(80,f.chip.gpu));}plan=enemyPlan();render();$('actions').querySelector('button').focus();}
function move(k){if(finished||p.energy<costs[k])return;const pk=k,ek=plan;const out=pk==='guard'?0:Math.round(damage(p,e,pk)*(ek==='guard'?.3:1));const incoming=ek==='guard'?0:Math.round(damage(e,p,ek)*(pk==='guard'?.3:1));p.hp=Math.max(0,p.hp-incoming);e.hp=Math.max(0,e.hp-out);for(const [f,m] of [[p,pk],[e,ek]])f.energy=Math.min(6,f.energy-costs[m]+(m==='guard'?3:0)+1);const entry=document.createElement('li');entry.textContent=`T${turn} — 自分：${labels[pk]} → ${out} / 相手：${labels[ek]} → ${incoming}`;$('log').prepend(entry);for(const id of ['p-card','e-card']){$(id).classList.remove('hit');void $(id).offsetWidth;$(id).classList.add('hit');}if(!p.hp||!e.hp||turn===20){finished=true;const verdict=p.hp===e.hp?'DRAW':p.hp>e.hp?'YOU WIN':'YOU LOSE';$('result').textContent=`${verdict} · ${p.hp} : ${e.hp}`;$('retry').hidden=false;}else{turn++;plan=enemyPlan();}render();}
$('start').addEventListener('click',start);$('retry').addEventListener('click',start);$('back').addEventListener('click',()=>{finished=true;$('setup').hidden=false;$('battle').hidden=true;$('start').focus();});$('swap').addEventListener('click',()=>{const old=$('player').value;$('player').value=$('enemy').value;$('enemy').value=old;compare();});for(const id of ['player','enemy'])$(id).addEventListener('change',compare);document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>move(b.dataset.move)));
async function init(){try{const response=await fetch('./index.html',{cache:'no-cache'});if(!response.ok)throw Error('HTTP '+response.status);const doc=new DOMParser().parseFromString(await response.text(),'text/html');const data=JSON.parse(doc.getElementById('chip-data').textContent);chips=data.filter(c=>c.chip.startsWith('M')&&c.platform==='mac'&&Object.keys(base).every(k=>Number.isFinite(c.bench?.[k])&&c.bench[k]>0));if(!chips.length)throw Error('no chips');for(const id of ['player','enemy']){for(const c of chips){const opt=document.createElement('option');opt.value=c.id;opt.textContent=`${c.chip} · ${c.cpu}CPU / ${c.gpu}GPU`;$(id).append(opt);}$(id).disabled=false;}$('player').value=(chips.find(c=>c.chip==='M1'&&c.gpu===8)||chips[0]).id;$('enemy').value=(chips.find(c=>c.chip==='M2'&&c.gpu===10)||chips.at(-1)).id;compare();$('start').disabled=false;$('swap').disabled=false;$('loading').textContent=`${chips.length}構成 · スコア比をゲーム用に調整した対戦です。`;}catch(error){$('loading').textContent='データを読み込めませんでした。ページを再読み込みしてください。';}}
init();
