'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let chips=[],baseline,enemyModels={},mode='normal',state='setup',run=null,W=960,H=600,last=0,raf=0,pointer=null,keys=new Set();
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const upgrades=[
{id:'damage',name:'並列演算',tag:'CPU',desc:'すべての通常弾の威力 +25%',apply:r=>r.damage*=1.25},
{id:'rate',name:'パイプライン',tag:'CPU',desc:'通常弾の発射間隔を15%短縮',apply:r=>r.interval=Math.max(.1,r.interval*.85)},
{id:'shots',name:'GPUクラスター',tag:'GPU',desc:'同時発射数 +1。弾幕を厚くする',apply:r=>r.shots=Math.min(12,r.shots+1)},
{id:'pierce',name:'貫通キャッシュ',tag:'GPU',desc:'弾がさらに1体の敵を貫通する',apply:r=>r.pierce++},
{id:'orbit',name:'サテライト',tag:'GPU',desc:'自分の周囲を回る攻撃衛星 +1',apply:r=>r.orbits=Math.min(6,r.orbits+1)},
{id:'cool',name:'放熱設計',tag:'THERMAL',desc:'熱の上昇を20%抑え、冷却を25%強化',apply:r=>{r.heatGain*=.8;r.cooling*=1.25;}},
{id:'heal',name:'メモリ拡張',tag:'MEMORY',desc:'最大HP +20。HPも35回復する',apply:r=>{r.maxHp+=20;r.hp=Math.min(r.maxHp,r.hp+35);}},
{id:'magnet',name:'広帯域バス',tag:'MEMORY',desc:'コア回収範囲 +65。経験値を集めやすく',apply:r=>r.magnet+=65},
{id:'dash',name:'高速スケジューラ',tag:'CPU',desc:'移動速度 +12%。ダッシュ再使用を20%短縮',apply:r=>{r.speed*=1.12;r.dashMax*=.8;}},
{id:'regen',name:'自己修復',tag:'MEMORY',desc:'毎秒HPを0.8回復する',apply:r=>r.regen+=.8}
];
function spec(c){const b=baseline.bench,s=c.bench;return{interval:.52/(1+.75*Math.log2(Math.max(1,s.single/b.single))),damage:14*(1+.48*Math.log2(Math.max(1,s.multi/b.multi))),shots:Math.min(6,1+Math.floor(Math.log2(Math.max(1,s.metal/b.metal)))),shield:Math.min(60,Math.max(0,Math.round(12*Math.log2(Math.max(...c.memory)/16))))};}
function selected(){return chips.find(c=>c.id===$('chip').value);}
function bestKey(){return 'silicon-arena-v2-'+selected().id+'-'+mode;}
function showBest(){let best=0;try{best=Number(localStorage.getItem(bestKey()))||0;}catch{}$('best').textContent=best?`この構成のBEST / ${best.toLocaleString()} pt`:'';}
function preview(){const c=selected(),s=spec(c);$('chipPreview').innerHTML=ChipArt.html(c.chip,'preview-art',true);ChipArt.prepare(c.chip);for(const n of ['A18 Pro','A19 Pro','M1 Max','M2 Ultra','M3 Ultra'])ChipArt.prepare(n);$('stats').replaceChildren();const values=[['発射間隔',s.interval.toFixed(2)+'s',clamp((.6-s.interval)/.6,0,1)],['弾の威力',Math.round(s.damage),clamp(s.damage/45,0,1)],['同時発射',s.shots+'発',s.shots/6],['シールド',s.shield,s.shield/60]];for(const [name,value,percent]of values){const el=document.createElement('div');el.className='stat';el.innerHTML=`<span>${name}</span><div class="stat-track"><i style="width:${percent*100}%"></i></div><b>${value}</b>`;$('stats').append(el);}const note=document.createElement('p');note.className='ratios';note.textContent=`実スコア M1比：Single ${(c.bench.single/baseline.bench.single).toFixed(2)}× / Multi ${(c.bench.multi/baseline.bench.multi).toFixed(2)}× / GPU ${(c.bench.metal/baseline.bench.metal).toFixed(2)}× · 最大${Math.max(...c.memory)}GB`;$('stats').append(note);showBest();}
function resize(){const rect=canvas.getBoundingClientRect();if(!rect.width)return;const oldW=W,oldH=H;W=rect.width;H=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(run){run.x=clamp(run.x/oldW*W,15,W-15);run.y=clamp(run.y/oldH*H,15,H-15);for(const group of [run.enemies,run.gems,run.bullets,run.hostile])for(const item of group){item.x=item.x/oldW*W;item.y=item.y/oldH*H;}}draw();}
function start(){const chip=selected(),s=spec(chip);state='running';pointer=null;keys.clear();$('setup').hidden=true;$('play').hidden=false;$('overlay').hidden=true;$('about').open=false;run={chip,...s,x:W/2,y:H/2,maxHp:100+s.shield,hp:100+s.shield,speed:175,heat:0,heatGain:30,cooling:23,oc:false,locked:false,regen:0,magnet:65,pierce:0,orbits:0,dash:0,dashCd:0,dashMax:3.2,dx:0,dy:-1,invuln:0,t:0,score:0,kills:0,xp:0,level:1,need:7,spawn:0,fire:.3,enemies:[],bullets:[],hostile:[],gems:[],particles:[],upgrades:{},bosses:0,spawnedBosses:0,toast:3,toastText:'移動して回避 · 攻撃は自動',orbitHit:0};resize();run.x=W/2;run.y=H/2;$('runChip').textContent=chip.chip;$('build').replaceChildren();hud();canvas.focus();last=0;if(!raf)raf=requestAnimationFrame(frame);}
function announce(text){run.toastText=text;run.toast=3;}
function showDialog(label,title,text,choices){pointer=null;keys.clear();$('dialogLabel').textContent=label;$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('choices').replaceChildren();for(const c of choices){const b=document.createElement('button');b.className='choice';const em=document.createElement('em');em.textContent=c.tag||'CONTINUE';const titleEl=document.createElement('b');titleEl.textContent=c.name;const d=document.createElement('span');d.textContent=c.desc||'';b.append(em,titleEl,d);b.addEventListener('click',c.action);$('choices').append(b);}$('overlay').hidden=false;$('choices').querySelector('button')?.focus();}
function resume(){state='running';$('overlay').hidden=true;last=0;canvas.focus();}
function pause(){if(state==='running'){state='paused';showDialog('PAUSED','一時停止','戦闘時間は止まっています。',[{name:'続ける',action:resume},{name:'構成を選び直す',tag:'EXIT',desc:'進行中のランを終了します',action:home}]);}else if(state==='paused')resume();}
function home(){state='setup';run=null;pointer=null;keys.clear();$('play').hidden=true;$('setup').hidden=false;$('overlay').hidden=true;showBest();$('start').focus();}
function levelUp(){run.xp-=run.need;run.level++;run.need=Math.round(7+run.level*3);state='upgrade';const pool=upgrades.filter(u=>!(u.id==='shots'&&run.shots>=12)&&!(u.id==='orbit'&&run.orbits>=6));for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}showDialog('CORE UPGRADE / LV.'+run.level,'次の強化を選ぶ','組み合わせで戦い方が変わる。',pool.slice(0,3).map(u=>({...u,action:()=>{u.apply(run);run.upgrades[u.id]=(run.upgrades[u.id]||0)+1;renderBuild();resume();if(run.xp>=run.need)levelUp();}})));}
function renderBuild(){$('build').replaceChildren();for(const [id,count]of Object.entries(run.upgrades)){const el=document.createElement('span');el.textContent=upgrades.find(u=>u.id===id).name+' ×'+count;$('build').append(el);}}
function end(win){state='ended';run.oc=false;run.score+=Math.floor(run.t)*10+(win?2000:0);let best=run.score;try{best=Math.max(Number(localStorage.getItem(bestKey()))||0,run.score);localStorage.setItem(bestKey(),String(best));}catch{}showDialog(win?'SYSTEM CLEAR':'SYSTEM HALTED',win?'アリーナ制圧。':'次は、違う構成で。',`${run.chip.chip} · ${Math.floor(run.t)}秒 · ${run.kills}撃破 · ${run.score.toLocaleString()} pt / BEST ${best.toLocaleString()}`,[{name:'もう一度出撃',tag:'RETRY',desc:'同じチップで新しいビルドを試す',action:start},{name:'チップを変える',tag:'LOADOUT',desc:'別の世代・コア構成を試す',action:home}]);hud();}
function dash(){if(state!=='running'||run.dashCd>0)return;run.dash=.16;run.invuln=.3;run.dashCd=run.dashMax;burst(run.x,run.y,'#8be8dd',8);}
function oc(){if(state!=='running'||run.locked)return;run.oc=!run.oc;}
function spawn(boss=false){const side=Math.floor(rand(0,4));let x=side===0?-25:side===1?W+25:rand(0,W),y=side===2?-25:side===3?H+25:rand(0,H);const r=run,difficulty=mode==='hard'?1.35:1;const stage=Math.floor(r.t/30);const kind=boss?'boss':r.t>15&&Math.random()<.28?'shooter':r.t>8&&Math.random()<.35?'fast':'normal';const model=kind==='normal'?enemyModels.a18:enemyModels.a19;const ratios=boss?{single:1,multi:1,metal:1}:model.ratios;const hp=(boss?380*(1+r.spawnedBosses*.45):(40+stage*20)*ratios.multi)*difficulty;const names=['M1 Max','M2 Ultra','M3 Ultra'];r.enemies.push({id:Math.random(),x,y,kind,hp,maxHp:hp,r:boss?30:kind==='normal'?13:15,speed:(boss?27:kind==='fast'?95+stage*12:44+stage*8)*ratios.single,damage:boss?25:12*ratios.metal,shotDamage:boss?10:10*ratios.metal,shotInterval:2.5/ratios.single,shoot:boss?1.5:rand(1,3),flash:0,name:boss?names[Math.min(r.spawnedBosses,2)]:model.name,orbitCd:0});if(boss){r.spawnedBosses++;announce(names[r.spawnedBosses-1]+' / BOSS');}}

function burst(x,y,color,n){if(reduced)return;for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),v=rand(20,110);run.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.2,.55),color});}if(run.particles.length>180)run.particles.splice(0,run.particles.length-180);}
function fire(){const r=run;let target=null,d=Infinity;for(const e of r.enemies){const m=dist(r,e);if(m<d){d=m;target=e;}}if(!target)return;const a=Math.atan2(target.y-r.y,target.x-r.x),count=r.shots+(r.oc?2:0);for(let i=0;i<count;i++){const angle=a+(i-(count-1)/2)*.15;r.bullets.push({x:r.x,y:r.y,vx:Math.cos(angle)*460,vy:Math.sin(angle)*460,life:1.8,damage:r.damage*(r.oc?1.25:1),left:1+r.pierce,hit:new Set()});}if(r.bullets.length>240)r.bullets.splice(0,r.bullets.length-240);}
function hit(amount){if(run.invuln>0)return;run.hp=Math.max(0,run.hp-amount);run.invuln=.65;burst(run.x,run.y,'#ff8c92',8);}
function kill(e){run.kills++;run.score+=e.kind==='boss'?600:25;run.gems.push({x:e.x,y:e.y,value:e.kind==='boss'?15:1});burst(e.x,e.y,e.kind==='boss'?'#bc9cfa':'#8be8dd',e.kind==='boss'?20:5);if(e.kind==='boss'){run.bosses++;announce('BOSS DOWN / コアを回収');}if(run.gems.length>160){const oldest=run.gems.shift();run.gems[0].value+=oldest.value;}}
function update(dt){const r=run;r.t+=dt;r.spawn-=dt;r.fire-=dt;r.invuln-=dt;r.dash-=dt;r.dashCd=Math.max(0,r.dashCd-dt);r.toast-=dt;r.hp=Math.min(r.maxHp,r.hp+r.regen*dt);if(r.oc){r.heat=Math.min(100,r.heat+r.heatGain*dt);if(r.heat>=100){r.oc=false;r.locked=true;announce('THERMAL LIMIT / 冷却中');}}else{r.heat=Math.max(0,r.heat-r.cooling*dt);if(r.heat<=20)r.locked=false;}
let mx=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0),my=(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('w')?1:0);if(pointer){mx=clamp((pointer.x-pointer.sx)/42,-1,1);my=clamp((pointer.y-pointer.sy)/42,-1,1);}const len=Math.hypot(mx,my);if(len>.08){mx/=Math.max(1,len);my/=Math.max(1,len);r.dx=mx;r.dy=my;}const speed=r.speed*(r.locked?.7:1);r.x=clamp(r.x+(r.dash>0?r.dx*speed*4.5:mx*speed)*dt,14,W-14);r.y=clamp(r.y+(r.dash>0?r.dy*speed*4.5:my*speed)*dt,14,H-14);
if(r.spawn<=0){const n=1+Math.floor(r.t/25)+(mode==='hard'?1:0);for(let i=0;i<n&&r.enemies.length<65;i++)spawn();r.spawn=Math.max(.38,1.1-r.t*.006);}if(r.spawnedBosses<3&&r.t>=[25,55,90][r.spawnedBosses])spawn(true);if(r.fire<=0){fire();r.fire=r.interval*(r.oc?.48:1)*(r.locked?1.5:1);}
for(const e of r.enemies){const a=Math.atan2(r.y-e.y,r.x-e.x),distance=dist(r,e);if(!(e.kind==='shooter'&&distance<180)){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;}e.flash-=dt;e.orbitCd-=dt;e.shoot-=dt;if(e.kind==='boss'&&e.shoot<=0){for(let i=0;i<12;i++){const angle=i/12*Math.PI*2+r.t*.2;r.hostile.push({x:e.x,y:e.y,vx:Math.cos(angle)*105,vy:Math.sin(angle)*105,life:5,damage:e.shotDamage});}e.shoot=2.2;}else if(e.kind==='shooter'&&e.shoot<=0){r.hostile.push({x:e.x,y:e.y,vx:Math.cos(a)*140,vy:Math.sin(a)*140,life:4,damage:e.shotDamage});e.shoot=e.shotInterval;}if(distance<e.r+11)hit(e.damage);for(let i=0;i<r.orbits&&e.orbitCd<=0;i++){const angle=r.t*2.5+i/r.orbits*Math.PI*2;if(Math.hypot(e.x-(r.x+Math.cos(angle)*58),e.y-(r.y+Math.sin(angle)*58))<e.r+9){e.hp-=24;e.flash=.1;e.orbitCd=.35;}}}
for(const b of r.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of r.enemies){if(e.hp<=0||b.hit.has(e.id)||b.left<=0)continue;if(dist(b,e)<e.r+5){e.hp-=b.damage;e.flash=.12;b.hit.add(e.id);b.left--;}}}for(const b of r.hostile){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(dist(b,r)<14){hit(b.damage);b.life=0;}}
for(const e of r.enemies)if(e.hp<=0)kill(e);r.enemies=r.enemies.filter(e=>e.hp>0);r.bullets=r.bullets.filter(b=>b.life>0&&b.left>0&&b.x>-50&&b.x<W+50&&b.y>-50&&b.y<H+50);r.hostile=r.hostile.filter(b=>b.life>0&&b.x>-50&&b.x<W+50&&b.y>-50&&b.y<H+50);if(r.hostile.length>240)r.hostile.splice(0,r.hostile.length-240);
for(const g of r.gems){const distance=dist(g,r);if(distance<r.magnet){const a=Math.atan2(r.y-g.y,r.x-g.x);g.x+=Math.cos(a)*Math.min(340*dt,distance);g.y+=Math.sin(a)*Math.min(340*dt,distance);}if(dist(g,r)<17){r.xp+=g.value;g.value=0;}}r.gems=r.gems.filter(g=>g.value>0);for(const p of r.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}r.particles=r.particles.filter(p=>p.life>0);
if(r.hp<=0){end(false);return;}if(r.bosses>=3){end(true);return;}if(r.t>=150){end(false);return;}if(r.xp>=r.need)levelUp();hud();}
function hud(){if(!run)return;const r=run;$('time').textContent=String(Math.floor(r.t/60)).padStart(2,'0')+':'+String(Math.floor(r.t%60)).padStart(2,'0');$('wave').textContent=r.t>=90?'FINAL BOSS':`WAVE ${String(1+Math.floor(r.t/15)).padStart(2,'0')}`;$('score').textContent=r.score.toLocaleString();$('health').max=r.maxHp;$('health').value=r.hp;$('healthText').textContent=Math.ceil(r.hp)+' / '+r.maxHp;$('heat').value=r.heat;$('heatText').textContent=r.locked?'LIMIT':Math.round(r.heat)+'%';$('xp').max=r.need;$('xp').value=r.xp;$('xpLabel').firstChild.textContent='CORE LV.'+r.level+' ';$('dash').disabled=state!=='running'||r.dashCd>0;$('dash').firstChild.textContent=r.dashCd>0?r.dashCd.toFixed(1)+'s ':'ダッシュ ';$('overclock').disabled=state!=='running'||r.locked;$('overclock').setAttribute('aria-pressed',String(r.oc));$('overclock').firstChild.textContent=r.locked?'冷却中 ':r.oc?'OC ON ':'OC ';$('banner').textContent=r.toast>0?r.toastText:r.t>=120?'TIME LIMIT / '+Math.ceil(150-r.t)+'s':'';}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b131f';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#172231';ctx.lineWidth=.6;ctx.beginPath();for(let x=0;x<W;x+=40){ctx.moveTo(x,0);ctx.lineTo(x,H);}for(let y=0;y<H;y+=40){ctx.moveTo(0,y);ctx.lineTo(W,y);}ctx.stroke();if(!run)return;const r=run;
for(const g of r.gems){ctx.fillStyle='#8be8dd';ctx.save();ctx.translate(g.x,g.y);ctx.rotate(Math.PI/4);ctx.fillRect(-3,-3,6,6);ctx.restore();}for(const b of r.bullets){ctx.strokeStyle=r.oc?'#f7ca8b':'#a1f7ed';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.018,b.y-b.vy*.018);ctx.stroke();}for(const b of r.hostile){ctx.fillStyle='#ff8794';ctx.beginPath();ctx.arc(b.x,b.y,4,0,7);ctx.fill();}
for(const e of r.enemies){ctx.save();ctx.translate(e.x,e.y);const size=e.r*2;ctx.fillStyle='#080808';roundRect(-e.r,-e.r,size,size,3);ctx.fill();if(!ChipArt.draw(ctx,e.name,-e.r,-e.r,size)){ctx.fillStyle='#ddd';ctx.font='8px -apple-system,sans-serif';ctx.textAlign='center';ctx.fillText(e.name,0,3);}ctx.strokeStyle=e.kind==='boss'?'#bda5dc':e.kind==='normal'?'#98666d':'#c9936d';ctx.lineWidth=e.flash>0?2:1;roundRect(-e.r-1,-e.r-1,size+2,size+2,3);ctx.stroke();ctx.font=(e.kind==='boss'?'bold 10px':'9px')+' -apple-system,sans-serif';ctx.textAlign='center';ctx.fillStyle='#e4dfe7';ctx.fillText(e.name,0,e.r+12);if(e.kind==='boss'){ctx.fillStyle='#554166';ctx.fillRect(-30,-43,60,3);ctx.fillStyle='#c3a4fc';ctx.fillRect(-30,-43,60*Math.max(0,e.hp/e.maxHp),3);}ctx.restore();}

for(let i=0;i<r.orbits;i++){const a=r.t*2.5+i/r.orbits*Math.PI*2;ctx.fillStyle='#baa0f7';ctx.beginPath();ctx.arc(r.x+Math.cos(a)*58,r.y+Math.sin(a)*58,7,0,7);ctx.fill();}ctx.save();ctx.translate(r.x,r.y);if(r.invuln>0){ctx.strokeStyle='#8be8dd';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,24,0,7);ctx.stroke();}ctx.fillStyle='#080808';roundRect(-16,-16,32,32,3);ctx.fill();if(!ChipArt.draw(ctx,r.chip.chip,-16,-16,32)){ctx.fillStyle='#eee';ctx.font='bold 9px -apple-system,sans-serif';ctx.textAlign='center';ctx.fillText(r.chip.chip,0,3);}ctx.strokeStyle=r.oc?'#ffd198':'#a7f9ee';ctx.lineWidth=1.5;roundRect(-17,-17,34,34,3);ctx.stroke();ctx.restore();for(const p of r.particles){ctx.globalAlpha=Math.min(1,p.life*3);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);}ctx.globalAlpha=1;
if(pointer){ctx.strokeStyle='#b9e8e04d';ctx.lineWidth=1;ctx.beginPath();ctx.arc(pointer.sx,pointer.sy,35,0,7);ctx.stroke();ctx.fillStyle='#b9e8e033';ctx.beginPath();ctx.arc(pointer.sx+clamp(pointer.x-pointer.sx,-35,35),pointer.sy+clamp(pointer.y-pointer.sy,-35,35),12,0,7);ctx.fill();}}
function frame(now){raf=0;const dt=last?Math.min((now-last)/1000,.033):0;last=now;if(state==='running')update(dt);if(state!=='setup')draw();raf=requestAnimationFrame(frame);}
canvas.addEventListener('pointerdown',e=>{if(state!=='running'||pointer)return;const b=canvas.getBoundingClientRect();pointer={id:e.pointerId,sx:e.clientX-b.left,sy:e.clientY-b.top,x:e.clientX-b.left,y:e.clientY-b.top};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const b=canvas.getBoundingClientRect();pointer.x=e.clientX-b.left;pointer.y=e.clientY-b.top;});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(pointer?.id===e.pointerId)pointer=null;});
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(state==='setup'||e.target.matches('select,input'))return;if(state==='running'&&['arrowup','arrowdown','arrowleft','arrowright',' ','w','a','s','d'].includes(k))e.preventDefault();if(e.repeat)return;if(k==='escape'||k==='p'){pause();return;}if(state!=='running')return;keys.add(k);if(k===' ')dash();if(k==='e')oc();});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();pointer=null;if(state==='running')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause();});window.addEventListener('resize',resize);$('start').addEventListener('click',start);$('pause').addEventListener('click',pause);$('dash').addEventListener('click',dash);$('overclock').addEventListener('click',oc);$('chip').addEventListener('change',preview);document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));showBest();}));
async function init(){try{const res=await fetch('./index.html',{cache:'no-cache'});if(!res.ok)throw Error(res.status);const doc=new DOMParser().parseFromString(await res.text(),'text/html');const data=JSON.parse(doc.getElementById('chip-data').textContent);const a18=data.find(c=>c.chip==='A18 Pro'&&c.platform==='ios'&&c.gpu===6),a19=data.find(c=>c.chip==='A19 Pro'&&c.platform==='ios'&&c.gpu===6);if(!a18||!a19||[a18,a19].some(c=>['single','multi','metal'].some(k=>!(c.bench[k]>0))))throw Error('Missing opponent data');enemyModels={a18:{name:'A18 Pro',ratios:{single:1,multi:1,metal:1}},a19:{name:'A19 Pro',ratios:Object.fromEntries(['single','multi','metal'].map(k=>[k,a19.bench[k]/a18.bench[k]]))}};chips=data.filter(c=>c.chip.startsWith('M')&&c.platform==='mac'&&['single','multi','metal'].every(k=>Number.isFinite(c.bench?.[k])&&c.bench[k]>0)&&c.memory.length);if(!chips.length)throw Error('No chips');baseline=chips.find(c=>c.chip==='M1'&&c.gpu===8);if(!baseline)throw Error('Missing baseline');for(const c of chips){const o=document.createElement('option');o.value=c.id;o.textContent=`${c.chip} · ${c.cpu} CPU / ${c.gpu} GPU`;$('chip').append(o);}$('chip').value=(chips.find(c=>c.chip==='M2'&&c.gpu===10)||baseline).id;preview();$('chip').disabled=false;$('start').disabled=false;$('loadStatus').textContent=`${chips.length}構成から選択 · 3体のボスを倒すとクリア（制限150秒）`;}catch(e){$('loadStatus').textContent='データを取得できませんでした。ページを再読み込みしてください。';}}
init();
